package net.caffeinemc.mods.sodium.client.render.chunk.lists;

import dev.vexor.radium.compat.mojang.minecraft.math.SectionPos;
import it.unimi.dsi.fastutil.ints.IntArrays;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.caffeinemc.mods.sodium.client.render.chunk.region.RenderRegion;
import net.caffeinemc.mods.sodium.client.render.viewport.Viewport;

public interface RenderListProvider extends SortItemsProvider {
    ObjectArrayList<ChunkRenderList> getUnsortedRenderLists();

    default SortedRenderLists createRenderLists(Viewport viewport) {
        SectionPos sectionPos = viewport.getChunkCoord();
        ObjectArrayList<ChunkRenderList> unsorted = this.getUnsortedRenderLists();

        // sort the regions by distance to fix rare region ordering problems.
        // regions need to be sorted even when the order is generated by a correctly traversed section tree
        // but sections don't need to be sorted within regions
        int cameraX = sectionPos.getX() >> RenderRegion.REGION_WIDTH_SH;
        int cameraY = sectionPos.getY() >> RenderRegion.REGION_HEIGHT_SH;
        int cameraZ = sectionPos.getZ() >> RenderRegion.REGION_LENGTH_SH;

        int size = unsorted.size();
        int[] sortItems = this.ensureSortItemsOfLength(size);

        for (int i = 0; i < size; i++) {
            RenderRegion region = unsorted.get(i).getRegion();
            int x = Math.abs(region.getX() - cameraX);
            int y = Math.abs(region.getY() - cameraY);
            int z = Math.abs(region.getZ() - cameraZ);
            sortItems[i] = (x + y + z) << 16 | i;
        }

        IntArrays.unstableSort(sortItems, 0, size);

        ObjectArrayList<ChunkRenderList> sorted = new ObjectArrayList<ChunkRenderList>(size);
        for (int i = 0; i < size; i++) {
            int key = sortItems[i];
            ChunkRenderList renderList = unsorted.get(key & 0xFFFF);
            sorted.add(renderList);
        }

        for (ChunkRenderList list : sorted) {
            list.prepareForRender(sectionPos, this);
        }

        return new SortedRenderLists(sorted);
    }
}
